augment: true
augment_method: null
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: false
    is_feature: false
    is_flatten: false
    last_block_stride: 2
  name: resnet18
batch_size: 128
classifier:
  kwargs:
    feat_dim: 512
    lambda_epi: 0.25
    num_classes: 351
    temperature: 0.2
    temperature_attn: 5.0
  name: RENet
data_root: /data/wzy/tiered_imagenet
deterministic: true
device_ids: 2
episode_size: 1
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/RENet.yaml
- backbones/resnet12.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.05
    milestones:
    - 60
    - 80
  name: MultiStepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
  other:
    emb_func: 0.1
parallel_part:
- emb_func
pretrain_path: null
query_num: 15
result_root: ./results
resume: true
resume_path: ./results/RENet-tiered_imagenet-resnet18-5-1-Dec-23-2021-11-54-17
save_interval: 10
save_part:
- emb_func
seed: 0
shot_num: 1
tag: null
tb_scale: 17.525
test_episode: 200
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
train_episode: 3505
use_memory: false
way_num: 5
