classifier:
  name: Baseline
  kwargs:
    inner_param:
      inner_optim:
        name: Adam
        kwargs:
          lr: 1e-3
      inner_train_iter: 100
      inner_batch_size: 4
    feat_dim: 64000
    num_class: 64
