classifier:
  name: SKDModel
  kwargs:
    feat_dim: 640
    num_class: 64
    gamma: 1.0
    alpha: 0.1
    is_distill: True
    emb_func_path: ./results/SKDModel-miniImageNet-resnet12-5-1-1615448697/checkpoints/emb_func_best.pth
    cls_classifier_path: ./results/SKDModel-miniImageNet-resnet12-5-1-1615448697/checkpoints/cls_classifier_best.pth
